CREATE TABLE pull_requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title        VARCHAR(255)                            NOT NULL,
    author       VARCHAR(255)                            NOT NULL,
    language     VARCHAR(255)                            NOT NULL,
    code_snippet CLOB                                    NOT NULL,
    description  VARCHAR(255),
    status       VARCHAR(255)                            NOT NULL,
    created_at   TIMESTAMP,
    updated_at   TIMESTAMP,
    CONSTRAINT pk_pull_requests PRIMARY KEY (id)
);

INSERT INTO pull_requests (title, author, language, code_snippet, description, status, created_at, updated_at)
VALUES ('Fix login null pointer', 'shreya', 'JAVA',
        'public class LoginService { public User login(String email) { return userRepo.findByEmail(email); } }',
        'Fixes NPE when user email is not found', 'DRAFT', NOW(), NOW());

INSERT INTO pull_requests (title, author, language, code_snippet, description, status, created_at, updated_at)
VALUES ('Add input validation', 'keya', 'PYTHON',
        'def validate_input(data): if not data: raise ValueError("Empty input") return True',
        'Adds basic input validation to API endpoints', 'IN_REVIEW', NOW(), NOW());

INSERT INTO pull_requests (title, author, language, code_snippet, description, status, created_at, updated_at)
VALUES ('Refactor button component', 'arundhati', 'JAVASCRIPT',
        'const Button = ({ label, onClick }) => { return <button onClick={onClick}>{label}</button>; };',
        'Cleans up the reusable button component', 'DRAFT', NOW(), NOW());
